### ISSUE TITLE
Add a CSS to give a roll to dice

### ISSUE THREAD

**Issue by vaishnavi-2901** [vaishnavi-2901/dice-game#1]
On clicking dice, there should be a roll 
We can either go with CSS or a gif to achive that

**Comment by nileshkmr99** [comment]
Hey @vishu1089 , I would like to work on this issue, can you please assign it to me?

**Comment by vishu1089** [comment]
Assigned, enjoy your task!

**Comment by nileshkmr99** [comment]
Hey @vaishnavi-2901 , Please review the PR, if it's fine then let's merge this else if any discussion is required let's do it.

**Comment by vaishnavi-2901** [comment]
Closing this!
