### ISSUE TITLE
Update Readme.md

### ISSUE THREAD

**Issue by vaishnavi-2901** [vaishnavi-2901/dice-game#2]

**Comment by nileshkmr99** [comment]
Let me update the README, please assign this issue to me!

**Comment by vaishnavi-2901** [comment]
Ok, let me know all the details you need.

You can take inspiration from this repo: https://github.com/SkaiLord/otakle

**Comment by nileshkmr99** [comment]
Thanks for sharing the resources!

And sure will get back to you if I need any kind of details!

**Comment by nileshkmr99** [comment]
Hey @vaishnavi-2901, Please review the PR, have updated the README.md file. 
If it's fine then let's merge this else if any discussion or improvement is required let's do it.
